# Quiz 11 - BigQuery SQL Joins  
### Bibek Thapa

In this notebook, I will:

- Explore two related tables from BigQuery public datasets  
- Join the tables using a common key  
- Demonstrate four different join types  
- Compare the results of INNER, LEFT, RIGHT, and FULL OUTER JOINs  
- Explain how each join works and what kind of rows it returns

In [2]:
from google.colab import auth
auth.authenticate_user()
print('Authenticated')

Authenticated

## Tables Used

For this notebook, I selected the following two tables from the `thelook_ecommerce` dataset:

- `bigquery-public-data.thelook_ecommerce.orders`
- `bigquery-public-data.thelook_ecommerce.users`

These tables can be joined using:

- `orders.user_id = users.id`

This relationship is appropriate because each order is associated with a user.

## Preview of the Orders Table

The query below shows a small sample of the `orders` table.

In [4]:
%%bigquery --project quiz11-bigquery-sql-joins

SELECT *
FROM `bigquery-public-data.thelook_ecommerce.orders`
LIMIT 10;

Query is running:   0%|          |

Downloading:   0%|          |

,order_id,user_id,status,gender,created_at,returned_at,shipped_at,delivered_at,num_of_item
0,1,1,Cancelled,F,2021-05-09 07:02:40+00:00,NaT,NaT,NaT,1
1,11,11,Cancelled,F,2025-06-02 19:43:16+00:00,NaT,NaT,NaT,1
2,27,26,Cancelled,F,2024-12-24 13:12:30+00:00,NaT,NaT,NaT,1
3,32,31,Cancelled,F,2025-07-27 09:25:49+00:00,NaT,NaT,NaT,2
4,34,31,Cancelled,F,2025-10-20 08:51:54+00:00,NaT,NaT,NaT,3
5,37,33,Cancelled,F,2023-01-16 07:02:32+00:00,NaT,NaT,NaT,1
6,40,35,Cancelled,F,2025-02-12 09:00:53+00:00,NaT,NaT,NaT,1
7,54,45,Cancelled,F,2025-01-10 14:29:49+00:00,NaT,NaT,NaT,2
8,67,60,Cancelled,F,2023-10-18 03:36:57+00:00,NaT,NaT,NaT,1
9,88,76,Cancelled,F,2022-08-27 10:39:25+00:00,NaT,NaT,NaT,1

## Preview of the Users Table

The query below shows a small sample of the `users` table.

In [5]:
%%bigquery --project quiz11-bigquery-sql-joins

SELECT *
FROM `bigquery-public-data.thelook_ecommerce.users`
LIMIT 10;

Query is running:   0%|          |

Downloading:   0%|          |

,id,first_name,last_name,email,age,gender,state,street_address,postal_code,city,country,latitude,longitude,traffic_source,created_at,user_geom
0,45422,Christopher,Snyder,christophersnyder@example.com,17,M,Acre,54483 Garcia Park Apt. 338,69980-000,null,Brasil,-8.065346,-72.870949,Search,2025-06-15 17:09:00+00:00,POINT(-72.87094866 -8.065346116)
1,94239,Lindsay,Bender,lindsaybender@example.org,70,F,Acre,7778 Nicholas Shore,69980-000,null,Brasil,-8.065346,-72.870949,Search,2025-03-21 18:22:00+00:00,POINT(-72.87094866 -8.065346116)
2,631,Samantha,Adams,samanthaadams@example.net,27,F,Acre,24969 Joanna Rapid,69980-000,null,Brasil,-8.065346,-72.870949,Search,2023-07-13 08:02:00+00:00,POINT(-72.87094866 -8.065346116)
3,80092,Joseph,Williams,josephwilliams@example.org,55,M,Acre,366 Jeremy Meadow,69980-000,null,Brasil,-8.065346,-72.870949,Organic,2026-03-02 09:57:10.559475+00:00,POINT(-72.87094866 -8.065346116)
4,67467,Amber,Kramer,amberkramer@example.net,13,F,Acre,9267 Randall Spur Apt. 351,69980-000,null,Brasil,-8.065346,-72.870949,Organic,2025-06-19 09:20:00+00:00,POINT(-72.87094866 -8.065346116)
5,4750,Julie,Lawson,julielawson@example.org,50,F,Acre,548 Eric Ferry Apt. 691,69980-000,null,Brasil,-8.065346,-72.870949,Organic,2021-01-27 04:38:00+00:00,POINT(-72.87094866 -8.065346116)
6,90184,Jonathan,Williams,jonathanwilliams@example.net,50,M,Acre,65292 William Mount,69980-000,null,Brasil,-8.065346,-72.870949,Search,2020-06-09 04:23:00+00:00,POINT(-72.87094866 -8.065346116)
7,94071,Barry,Roberts,barryroberts@example.com,44,M,Acre,0738 Samantha Islands Suite 100,69970-000,Tarauacá,Brasil,-8.325245,-71.553030,Search,2023-01-28 14:19:00+00:00,POINT(-71.55302951 -8.325245103)
8,99813,Tina,Gill,tinagill@example.net,65,F,Acre,17074 Paula Harbors,69970-000,Tarauacá,Brasil,-8.325245,-71.553030,Organic,2020-01-31 03:22:00+00:00,POINT(-71.55302951 -8.325245103)
9,29847,Stephanie,Blevins,stephanieblevins@example.org,61,F,Acre,8712 Williams Place,69970-000,Tarauacá,Brasil,-8.325245,-71.553030,Search,2019-07-19 01:38:00+00:00,POINT(-71.55302951 -8.325245103)

## INNER JOIN

An INNER JOIN returns only the rows that have matching values in both tables.

In this example, only orders with a matching user record are returned.

In [16]:
%%bigquery --project quiz11-bigquery-sql-joins

SELECT
  o.order_id,
  o.user_id,
  o.status,
  u.first_name,
  u.last_name,
  u.email
FROM `bigquery-public-data.thelook_ecommerce.orders` AS o
INNER JOIN `bigquery-public-data.thelook_ecommerce.users` AS u
  ON o.user_id = u.id
LIMIT 20;

Query is running:   0%|          |

Downloading:   0%|          |

,order_id,user_id,status,first_name,last_name,email
0,1,1,Cancelled,Meghan,Mccormick,meghanmccormick@example.com
1,11,11,Cancelled,Cynthia,Garcia,cynthiagarcia@example.org
2,27,26,Cancelled,Michelle,Reynolds,michellereynolds@example.com
3,32,31,Cancelled,Caroline,Rose,carolinerose@example.net
4,34,31,Cancelled,Caroline,Rose,carolinerose@example.net
5,37,33,Cancelled,Brittany,Thompson,brittanythompson@example.org
6,40,35,Cancelled,Belinda,Torres,belindatorres@example.com
7,54,45,Cancelled,Ruth,Mccormick,ruthmccormick@example.org
8,67,60,Cancelled,Nancy,Hubbard,nancyhubbard@example.org
9,88,76,Cancelled,Marie,Contreras,mariecontreras@example.org
10,101,84,Cancelled,Stefanie,Thomas,stefaniethomas@example.com
11,102,84,Cancelled,Stefanie,Thomas,stefaniethomas@example.com
12,122,97,Cancelled,Kaylee,Jackson,kayleejackson@example.net
13,135,104,Cancelled,Lisa,Cooke,lisacooke@example.com
14,139,106,Cancelled,Dawn,Hunt,dawnhunt@example.com
15,141,108,Cancelled,Theresa,Summers,theresasummers@example.net
16,152,118,Cancelled,Sarah,Mooney,sarahmooney@example.net
17,160,124,Cancelled,Laurie,Nielsen,laurienielsen@example.com
18,162,124,Cancelled,Laurie,Nielsen,laurienielsen@example.com
19,189,142,Cancelled,Mary,Jenkins,maryjenkins@example.com

## LEFT JOIN

A LEFT JOIN returns all rows from the left table and matching rows from the right table.

If no match exists in the right table, the result shows `NULL` for the right-side columns.

Here, all rows from `orders` are kept.

In [17]:
%%bigquery --project quiz11-bigquery-sql-joins

SELECT
  o.order_id,
  o.user_id,
  o.status,
  u.first_name,
  u.last_name,
  u.email
FROM `bigquery-public-data.thelook_ecommerce.orders` AS o
LEFT JOIN `bigquery-public-data.thelook_ecommerce.users` AS u
  ON o.user_id = u.id
LIMIT 20;

Query is running:   0%|          |

Downloading:   0%|          |

,order_id,user_id,status,first_name,last_name,email
0,1,1,Cancelled,Meghan,Mccormick,meghanmccormick@example.com
1,11,11,Cancelled,Cynthia,Garcia,cynthiagarcia@example.org
2,27,26,Cancelled,Michelle,Reynolds,michellereynolds@example.com
3,32,31,Cancelled,Caroline,Rose,carolinerose@example.net
4,34,31,Cancelled,Caroline,Rose,carolinerose@example.net
5,37,33,Cancelled,Brittany,Thompson,brittanythompson@example.org
6,40,35,Cancelled,Belinda,Torres,belindatorres@example.com
7,54,45,Cancelled,Ruth,Mccormick,ruthmccormick@example.org
8,67,60,Cancelled,Nancy,Hubbard,nancyhubbard@example.org
9,88,76,Cancelled,Marie,Contreras,mariecontreras@example.org
10,101,84,Cancelled,Stefanie,Thomas,stefaniethomas@example.com
11,102,84,Cancelled,Stefanie,Thomas,stefaniethomas@example.com
12,122,97,Cancelled,Kaylee,Jackson,kayleejackson@example.net
13,135,104,Cancelled,Lisa,Cooke,lisacooke@example.com
14,139,106,Cancelled,Dawn,Hunt,dawnhunt@example.com
15,141,108,Cancelled,Theresa,Summers,theresasummers@example.net
16,152,118,Cancelled,Sarah,Mooney,sarahmooney@example.net
17,160,124,Cancelled,Laurie,Nielsen,laurienielsen@example.com
18,162,124,Cancelled,Laurie,Nielsen,laurienielsen@example.com
19,189,142,Cancelled,Mary,Jenkins,maryjenkins@example.com

## RIGHT JOIN

A RIGHT JOIN returns all rows from the right table and matching rows from the left table.

If no match exists in the left table, the result shows `NULL` for the left-side columns.

Here, all rows from `users` are kept.

In [18]:
%%bigquery --project quiz11-bigquery-sql-joins

SELECT
  o.order_id,
  o.user_id,
  o.status,
  u.id AS user_id,
  u.first_name,
  u.last_name,
  u.email
FROM `bigquery-public-data.thelook_ecommerce.orders` AS o
RIGHT JOIN `bigquery-public-data.thelook_ecommerce.users` AS u
  ON o.user_id = u.id
LIMIT 20;

Query is running:   0%|          |

Downloading:   0%|          |

,order_id,user_id,status,user_id_1,first_name,last_name,email
0,1,1,Cancelled,1,Meghan,Mccormick,meghanmccormick@example.com
1,11,11,Cancelled,11,Cynthia,Garcia,cynthiagarcia@example.org
2,27,26,Cancelled,26,Michelle,Reynolds,michellereynolds@example.com
3,32,31,Cancelled,31,Caroline,Rose,carolinerose@example.net
4,34,31,Cancelled,31,Caroline,Rose,carolinerose@example.net
5,37,33,Cancelled,33,Brittany,Thompson,brittanythompson@example.org
6,40,35,Cancelled,35,Belinda,Torres,belindatorres@example.com
7,54,45,Cancelled,45,Ruth,Mccormick,ruthmccormick@example.org
8,67,60,Cancelled,60,Nancy,Hubbard,nancyhubbard@example.org
9,88,76,Cancelled,76,Marie,Contreras,mariecontreras@example.org
10,101,84,Cancelled,84,Stefanie,Thomas,stefaniethomas@example.com
11,102,84,Cancelled,84,Stefanie,Thomas,stefaniethomas@example.com
12,122,97,Cancelled,97,Kaylee,Jackson,kayleejackson@example.net
13,135,104,Cancelled,104,Lisa,Cooke,lisacooke@example.com
14,139,106,Cancelled,106,Dawn,Hunt,dawnhunt@example.com
15,141,108,Cancelled,108,Theresa,Summers,theresasummers@example.net
16,152,118,Cancelled,118,Sarah,Mooney,sarahmooney@example.net
17,160,124,Cancelled,124,Laurie,Nielsen,laurienielsen@example.com
18,162,124,Cancelled,124,Laurie,Nielsen,laurienielsen@example.com
19,189,142,Cancelled,142,Mary,Jenkins,maryjenkins@example.com

## FULL OUTER JOIN

A FULL OUTER JOIN returns all rows from both tables.

Matching rows are combined. Non-matching rows from either side are also included, with `NULL` values where data is missing.

In [19]:
%%bigquery --project quiz11-bigquery-sql-joins

SELECT
  o.order_id,
  o.user_id,
  o.status,
  u.id AS user_id,
  u.first_name,
  u.last_name,
  u.email
FROM `bigquery-public-data.thelook_ecommerce.orders` AS o
FULL OUTER JOIN `bigquery-public-data.thelook_ecommerce.users` AS u
  ON o.user_id = u.id
LIMIT 20;

Query is running:   0%|          |

Downloading:   0%|          |

,order_id,user_id,status,user_id_1,first_name,last_name,email
0,1,1,Cancelled,1,Meghan,Mccormick,meghanmccormick@example.com
1,11,11,Cancelled,11,Cynthia,Garcia,cynthiagarcia@example.org
2,27,26,Cancelled,26,Michelle,Reynolds,michellereynolds@example.com
3,32,31,Cancelled,31,Caroline,Rose,carolinerose@example.net
4,34,31,Cancelled,31,Caroline,Rose,carolinerose@example.net
5,37,33,Cancelled,33,Brittany,Thompson,brittanythompson@example.org
6,40,35,Cancelled,35,Belinda,Torres,belindatorres@example.com
7,54,45,Cancelled,45,Ruth,Mccormick,ruthmccormick@example.org
8,67,60,Cancelled,60,Nancy,Hubbard,nancyhubbard@example.org
9,88,76,Cancelled,76,Marie,Contreras,mariecontreras@example.org
10,101,84,Cancelled,84,Stefanie,Thomas,stefaniethomas@example.com
11,102,84,Cancelled,84,Stefanie,Thomas,stefaniethomas@example.com
12,122,97,Cancelled,97,Kaylee,Jackson,kayleejackson@example.net
13,135,104,Cancelled,104,Lisa,Cooke,lisacooke@example.com
14,139,106,Cancelled,106,Dawn,Hunt,dawnhunt@example.com
15,141,108,Cancelled,108,Theresa,Summers,theresasummers@example.net
16,152,118,Cancelled,118,Sarah,Mooney,sarahmooney@example.net
17,160,124,Cancelled,124,Laurie,Nielsen,laurienielsen@example.com
18,162,124,Cancelled,124,Laurie,Nielsen,laurienielsen@example.com
19,189,142,Cancelled,142,Mary,Jenkins,maryjenkins@example.com

## Comparing row counts for all four joins

This query summarizes the number of rows returned by each join type.

In [10]:
%%bigquery --project quiz11-bigquery-sql-joins

SELECT 'INNER JOIN' AS join_type, COUNT(*) AS row_count
FROM `bigquery-public-data.thelook_ecommerce.orders` AS o
INNER JOIN `bigquery-public-data.thelook_ecommerce.users` AS u
  ON o.user_id = u.id

UNION ALL

SELECT 'LEFT JOIN' AS join_type, COUNT(*) AS row_count
FROM `bigquery-public-data.thelook_ecommerce.orders` AS o
LEFT JOIN `bigquery-public-data.thelook_ecommerce.users` AS u
  ON o.user_id = u.id

UNION ALL

SELECT 'RIGHT JOIN' AS join_type, COUNT(*) AS row_count
FROM `bigquery-public-data.thelook_ecommerce.orders` AS o
RIGHT JOIN `bigquery-public-data.thelook_ecommerce.users` AS u
  ON o.user_id = u.id

UNION ALL

SELECT 'FULL OUTER JOIN' AS join_type, COUNT(*) AS row_count
FROM `bigquery-public-data.thelook_ecommerce.orders` AS o
FULL OUTER JOIN `bigquery-public-data.thelook_ecommerce.users` AS u
  ON o.user_id = u.id;

Query is running:   0%|          |

Downloading:   0%|          |

         join_type  row_count
0       INNER JOIN     125676
1        LEFT JOIN     125676
2       RIGHT JOIN     145760
3  FULL OUTER JOIN     145760

# Summary

The notebook demonstrated four SQL joins using the `orders` and `users` tables:

- INNER JOIN
- LEFT JOIN
- RIGHT JOIN
- FULL OUTER JOIN

These joins help us understand how matching and non-matching records are handled when combining related tables.